CREATE TABLE Student
(Nr_albumu CHAR(6) PRIMARY KEY CHECK(ISNUMERIC(Nr_albumu)=1 AND LEN(Nr_albumu)=6),
Wydzial VARCHAR(255),
Kierunek VARCHAR(255),
Data_rozpoczecia_studiow DATE,
Imie VARCHAR(35) CHECK(PATINDEX('[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%', Imie COLLATE Latin1_General_CS_AS)=1 AND LEN(Imie)>0),
Nazwisko VARCHAR(35) CHECK(PATINDEX('[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%', Nazwisko COLLATE Latin1_General_CS_AS)=1 AND LEN(Nazwisko)>0),
Data_urodzenia DATE);

CREATE TABLE Pracownik
(PESEL CHAR(11) PRIMARY KEY CHECK(ISNUMERIC(PESEL)=1 AND LEN(PESEL)=11),
Imie VARCHAR(35) CHECK(PATINDEX('[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%', Imie COLLATE Latin1_General_CS_AS)=1 AND LEN(Imie)>0),
Nazwisko VARCHAR(35) CHECK(PATINDEX('[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%', Nazwisko COLLATE Latin1_General_CS_AS)=1 AND LEN(Nazwisko)>0),
Stanowisko VARCHAR(255) CHECK(LEN(Stanowisko)>0));

CREATE TABLE Wniosek
(nr INT IDENTITY(1,1) PRIMARY KEY,
Student_nr_albumu CHAR(6) FOREIGN KEY REFERENCES Student(Nr_albumu) ON DELETE CASCADE ON UPDATE CASCADE,
Status BIT CHECK(Status IN (0,1)),
Liczba_miesiecy INT CHECK (Liczba_miesiecy > 0),
Data DATE,
Pracownik_PESEL CHAR(11) FOREIGN KEY REFERENCES Pracownik(PESEL) ON DELETE CASCADE ON UPDATE CASCADE,
Nr_konta CHAR(26) CHECK(ISNUMERIC(Nr_konta)=1 AND LEN(Nr_konta)=26),
Wartosc DECIMAL(7,3));

CREATE TABLE Odwolanie
(Nr_wniosku INT PRIMARY KEY FOREIGN KEY REFERENCES Wniosek(nr) ON DELETE CASCADE ON UPDATE CASCADE,
Data DATE,
Powod VARCHAR(1000));

CREATE TABLE Wyplata
(nr_wyplaty INT IDENTITY(1,1) PRIMARY KEY,
Data DATE,
Wniosek_nr INT FOREIGN KEY REFERENCES Wniosek(nr) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Orzeczenie
(nr INT IDENTITY(1,1) PRIMARY KEY,
Data DATE,
Uzasadnienie VARCHAR(2000),
Liczba_miesiecy INT CHECK(Liczba_miesiecy > 0));

CREATE TABLE Stypendium_dla_osob_niepelnosprawnych
(nr INT PRIMARY KEY FOREIGN KEY REFERENCES Wniosek(nr) ON DELETE CASCADE ON UPDATE CASCADE,
nr_orzeczenia INT FOREIGN KEY REFERENCES Orzeczenie(nr) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Stypendium_rektora
(nr INT PRIMARY KEY FOREIGN KEY REFERENCES Wniosek(nr) ON DELETE CASCADE ON UPDATE CASCADE,
Srednia_ocen DECIMAL(3,2) CHECK(Srednia_ocen > 0.0 AND Srednia_ocen <= 5.0));

CREATE TABLE Zwiekszenie
(nr INT IDENTITY(1,1) PRIMARY KEY,
Kwota DECIMAL(7,3),
Sytuacja VARCHAR(1000));

CREATE TABLE Stypendium_socjalne
(nr INT PRIMARY KEY FOREIGN KEY REFERENCES Wniosek(nr) ON DELETE CASCADE ON UPDATE CASCADE,
Miesieczny_dochod_rodziny DECIMAL(9,3),
Liczba_osob INT CHECK(Liczba_osob > 0),
zwiekszenie_nr INT FOREIGN KEY REFERENCES Zwiekszenie(nr) ON DELETE CASCADE ON UPDATE CASCADE);








DECLARE @Sql NVARCHAR(500) DECLARE @Cursor CURSOR

SET @Cursor = CURSOR FAST_FORWARD FOR
SELECT DISTINCT sql = 'ALTER TABLE [' + tc2.TABLE_SCHEMA + '].[' +  tc2.TABLE_NAME + '] DROP [' + rc1.CONSTRAINT_NAME + '];'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME =rc1.CONSTRAINT_NAME

OPEN @Cursor FETCH NEXT FROM @Cursor INTO @Sql

WHILE (@@FETCH_STATUS = 0)
BEGIN
Exec sp_executesql @Sql
FETCH NEXT FROM @Cursor INTO @Sql
END

CLOSE @Cursor DEALLOCATE @Cursor
GO

EXEC sp_MSforeachtable 'DROP TABLE ?'
GO